version: '3'
services:
  proxy.local.crossbar.com:
    container_name: proxy.local.crossbar.com
    image: jwilder/nginx-proxy:alpine
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro"
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      main:
        aliases:
          - proxy.local.crossbar.com

  crossbar.local.crossbar.com:
    container_name: crossbar.local.crossbar.com
    image: crossbario/crossbar
    volumes:
      - "$PWD:/node:rw"
    ports:
      - 8080
    environment:
      VIRTUAL_HOST: 'crossbar.local.crossbar.com'
      VIRTUAL_PORT: 8080
      PORT: 8080
    restart: unless-stopped
    user: '0'
    # command: 'sleep 5d'
    networks:
      main:
        aliases:
          - crossbar.local.crossbar.com

  emitter.local.crossbar.com:
    container_name: emitter.local.crossbar.com
    image: nodejs-serve
    restart: always
    volumes:
      - "./emitter/:/opt/app-root/src/:rw"
    ports:
      - 80
    environment:
      VIRTUAL_HOST: 'emitter.local.crossbar.com'
      PORT: 80
    command: 'serve -l 80'
    networks:
      main:
        aliases:
          - emitter.local.crossbar.com

  receiver.local.crossbar.com:
    container_name: receiver.local.crossbar.com
    image: nodejs-serve
    restart: always
    ports:
      - 80
    volumes:
      - "./receiver:/opt/app-root/src:rw"
    environment:
      VIRTUAL_HOST: 'receiver.local.crossbar.com'
      VIRTUAL_PORT: 80
    command: 'serve -l 80'
    networks:
      main:
        aliases:
          - receiver.local.crossbar.com

networks:
  main: